name: Build Blender Python Module

on:
  workflow_dispatch:
    inputs:
      blender_version:
        description: "Version"
        required: true
        default: "3.3.0"
      python_version:
        description: "Python"
        required: true
        default: "3.10"
      cuda:
        description: "CUDA"
        required: true
        default: "yes"
      runner:
        description: "Runner"
        required: true
        default: "ubuntu-20.04"

jobs:
  build_blender:
    name: Build Blender Python Module Job
    runs-on: ${{ github.event.inputs.runner }}
    env:
      BLENDER_VERSION: ${{ github.event.inputs.blender_version }}
    steps:
      - name: Info
        run: |
          echo Building Blender Python module version $BLENDER_VERSION
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
              build-essential \
              git \
              subversion \
              cmake \
              libx11-dev \
              libxxf86vm-dev \
              libxcursor-dev \
              libxi-dev \
              libxrandr-dev \
              libxinerama-dev \
              libglew-dev \
              python3
      - name: Install CUDA toolkit 11.4.0
        if: ${{ github.event.inputs.cuda == 'yes' }}
        uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.4.0'
          linux-local-args: '["--toolkit"]'
      - name: Enable CUDA build option
        if: ${{ github.event.inputs.cuda == 'yes' }}
        run: |
          BUILD_CMAKE_ARGS="BUILD_CMAKE_ARGS=\"-D WITH_CYCLES_CUDA_BINARIES=ON\""
          echo "BUILD_CMAKE_ARGS=$BUILD_CMAKE_ARGS" >> $GITHUB_ENV          
      - name: Checkout Blender sources from GitHub
        uses: actions/checkout@v2
        with:
          repository: "blender/blender"
          path: blender-build/blender
          ref: "v${{ env.BLENDER_VERSION }}"
          submodules: false # use official Blender method to update submodules
      - name: Store code SHA
        run: |
          cd blender-build/blender
          BLENDER_CODE_SHA=`git rev-parse --short HEAD`
          echo Using Blender code version $BLENDER_CODE_SHA
          echo "BLENDER_CODE_SHA=$BLENDER_CODE_SHA" >> $GITHUB_ENV
      - name: Checkout Blender submodules
        run: |
          cd blender-build/blender
          VERSION=${BLENDER_VERSION%.*}
          git switch -c blender-v$VERSION-release
          make update ${{ env.BUILD_CMAKE_ARGS }}           
      - name: Checkout precompiled library dependencies
        run: |
          VERSION=${BLENDER_VERSION%.*}
          mkdir blender-build/lib
          cd blender-build/lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-$VERSION-release/lib/linux_centos7_x86_64
      - name: Build system preparation
        # Blender 2.93.5 needs gcc 9.3+ toolchain. Available by default in Ubuntu 20.04 runners but needs setup for Ubuntu 18.04.
        if: ${{ github.event.inputs.runner == 'ubuntu-18.04' }}
        run: |
          echo Use gcc 9 toolchain
          echo "CC=gcc-9" >> $GITHUB_ENV        
          echo "CXX=g++-9" >> $GITHUB_ENV
      - name: Build Blender bpy.so
        run: |
          cd blender-build/blender
          make bpy ${{ env.BUILD_CMAKE_ARGS }}
      - name: Compress compiled Blender build
        run: |
          VERSION=${BLENDER_VERSION%.*}
          mkdir release
          tar Jcf release/blender-bpy-$BLENDER_VERSION-python${{ github.event.inputs.python_version }}-${{ github.event.inputs.runner }}.tar.xz -C blender-build/lib/linux_centos7_x86_64/python/lib/python${{ github.event.inputs.python_version }}/site-packages/ bpy.so $VERSION/
      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum blender-bpy-$BLENDER_VERSION-python${{ github.event.inputs.python_version }}-${{ github.event.inputs.runner }}.tar.xz > blender-bpy-$BLENDER_VERSION-python${{ github.event.inputs.python_version }}-${{ github.event.inputs.runner }}.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: blender-bpy-${{ env.BLENDER_VERSION }}-python${{ github.event.inputs.python_version }}-${{ github.event.inputs.runner }}-${{ env.BLENDER_CODE_SHA }}
          path: "release"
