name: Build Blender Application

on:
  workflow_dispatch:

jobs:
  build_blender:
    name: Build Blender Application Job
    runs-on: ubuntu-20.04
    env:
      BLENDER_VERSION: 2.93.5
    steps:
      - name: Info
        run: |
          echo Building Blender version $BLENDER_VERSION
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
              build-essential \
              git \
              subversion \
              cmake \
              libx11-dev \
              libxxf86vm-dev \
              libxcursor-dev \
              libxi-dev \
              libxrandr-dev \
              libxinerama-dev \
              libglew-dev \
              python3
      - name: Checkout Blender sources from GitHub
        uses: actions/checkout@v2
        with:
          repository: "blender/blender"
          path: blender-build/blender
          ref: "v${{ env.BLENDER_VERSION }}"
          submodules: recursive
      - name: Checkout precompiled library dependencies
        run: |
          VERSION=${BLENDER_VERSION%.*}
          mkdir blender-build/lib
          cd blender-build/lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-$VERSION-release/lib/linux_centos7_x86_64
      - name: Build Blender
        run: |
          cd blender-build/blender
          make release
      - name: Compress compiled Blender build
        run: |
          mkdir release
          cp -r blender-build/build_linux_release/bin release/blender
          cd release
          tar Jcf blender-$BLENDER_VERSION.tar.xz blender
          rm -rf blender
      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum blender-$BLENDER_VERSION.tar.xz > blender-$BLENDER_VERSION.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: blender-${{ env.BLENDER_VERSION }}
          path: "release"
          
