name: Build Blender Python Module

on:
  workflow_dispatch:
    inputs:
      blender_version:
        description: "Version"
        required: true
        default: "2.93.5"
      runner:
        description: "Runner"
        required: true
        default: "ubuntu-20.04"

jobs:
  build_blender:
    name: Build Blender Python Module Job
    runs-on: ${{ github.event.inputs.runner }}
    env:
      BLENDER_VERSION: ${{ github.event.inputs.blender_version }}
    steps:
      - name: Info
        run: |
          echo Building Blender Python module version $BLENDER_VERSION
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
              build-essential \
              git \
              subversion \
              cmake \
              libx11-dev \
              libxxf86vm-dev \
              libxcursor-dev \
              libxi-dev \
              libxrandr-dev \
              libxinerama-dev \
              libglew-dev \
              python3
      - name: Checkout Blender sources from GitHub
        uses: actions/checkout@v2
        with:
          repository: "blender/blender"
          path: blender-build/blender
          ref: "v${{ env.BLENDER_VERSION }}"
          submodules: recursive
      - name: Checkout precompiled library dependencies
        run: |
          VERSION=${BLENDER_VERSION%.*}
          mkdir blender-build/lib
          cd blender-build/lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-$VERSION-release/lib/linux_centos7_x86_64
      - name: Build Blender bpy.so
        run: |
          cd blender-build/blender
          make bpy
      - name: Compress compiled Blender build
        run: |
          VERSION=${BLENDER_VERSION%.*}
          mkdir release
          tar Jcf release/blender-bpy-$BLENDER_VERSION.tar.xz -C blender-build/lib/linux_centos7_x86_64/python/lib/python3.9/site-packages/ bpy.so $VERSION/
      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum blender-bpy-$BLENDER_VERSION.tar.xz > blender-bpy-$BLENDER_VERSION.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: blender-bpy-${{ env.BLENDER_VERSION }}
          path: "release"
          
